version : '3'
services:
  app:
    container_name: agenda
    restart: always
    build: . # current dir
    ports:
      - '80:3000'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'